### ISSUE TITLE
Camera patch causes build failure

### ISSUE THREAD

**Issue by piggz** [mer-hybris/hybris-patches#8]
The patch hybris-16.0/frameworks/av/0001-hybris-AudioService-is-disabled-in-hybris-adaptation.patch leaves the parameter "kind" unused, which, on my linueagos causes the build to fail as the flags -Werror and -Wunused-parameter are used.

I worked around it by adding the kind parameter to the log statement LOG1("CameraService::loadSoundLocked ref=%d kind=%d", mSoundRef, kind);

**Comment by JamiKettunen** [comment]
I suppose this can be closed as #9 is now merged :)
